package com.dacare.evidence;

import java.net.URI;
import java.time.LocalDateTime;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionSynchronizationManager;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.web.client.RestClient;

/**
 * 장애 복구 실험에만 사용하는 Outbox 구현이다. 예약 트랜잭션에 발송 요청을 기록하고,
 * 별도 작업자가 성공할 때까지 요청을 유지하는 방식을 검증한다.
 */
public class OutboxPrototype {

  private final JdbcTemplate jdbc;
  private final TransactionTemplate transaction;
  private final RestClient client = RestClient.create();
  private final String endpoint;

  public OutboxPrototype(JdbcTemplate jdbc, PlatformTransactionManager manager, String endpoint) {
    if (!"127.0.0.1".equals(URI.create(endpoint).getHost())) {
      throw new IllegalArgumentException("실험용 발송은 로컬 테스트 서버만 허용합니다.");
    }
    this.jdbc = jdbc;
    this.transaction = new TransactionTemplate(manager);
    this.endpoint = endpoint;
    jdbc.execute("""
        CREATE TABLE IF NOT EXISTS notification_outbox (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          reservation_id BIGINT NOT NULL REFERENCES reservation(id),
          message VARCHAR(2000) NOT NULL,
          status VARCHAR(20) NOT NULL
        )
        """);
  }

  public void enqueue(Long reservationId) {
    if (!TransactionSynchronizationManager.isActualTransactionActive()) {
      throw new IllegalStateException("예약과 동일한 트랜잭션에서 기록해야 합니다.");
    }
    jdbc.update("INSERT INTO notification_outbox(reservation_id, message, status) VALUES (?, ?, 'PENDING')",
        reservationId, "예약 접수 #" + reservationId);
  }

  @Scheduled(fixedDelayString = "${app.notification.poll-delay:100}")
  public void processPending() {
    var requests = jdbc.queryForList("SELECT id, reservation_id, message FROM notification_outbox WHERE status = 'PENDING' ORDER BY id");
    for (var request : requests) {
      try {
        client.post().uri(endpoint).body(java.util.Map.of("text", request.get("message")))
            .retrieve().toBodilessEntity();
        transaction.executeWithoutResult(status -> {
          jdbc.update("""
              INSERT INTO notification_history(reservation_id, channel, status, message, created_at)
              VALUES (?, 'SLACK', 'SUCCESS', ?, ?)
              """, request.get("reservation_id"), request.get("message"), LocalDateTime.now());
          jdbc.update("UPDATE notification_outbox SET status = 'SUCCESS' WHERE id = ?", request.get("id"));
        });
      } catch (RuntimeException exception) {
        System.out.println("[실험용 Outbox] 처리 실패 / 요청 유지 / 오류 유형=" + exception.getClass().getSimpleName());
      }
    }
  }
}
