CREATE TABLE api_usage (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    api VARCHAR(30) NOT NULL,
    usage_date DATE NOT NULL,
    used INTEGER NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_api_usage_api_date UNIQUE (api, usage_date)
);
